[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = "full"

[dependencies]
bimap = "0.6.3"
bitflags = "2.6.0"
itertools = "0.13.0"
lazy_static = "1.5.0"
petgraph = "0.6.5"
priority-queue = "2.1.1"
seq-macro = "0.3.5"
utf8-read = "0.4.0"
