[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = "full"

[dependencies]
bitflags = "2.6.0"
itertools = "0.13.0"
priority-queue = "2.1.1"
seq-macro = "0.3.5"
utf8-read = "0.4.0"
